import java.util.List;
import javax.swing.JOptionPane;

public class AdminDashboardForm extends javax.swing.JFrame {
     private UserManager userManager;
    
    public AdminDashboardForm(UserManager userManager) {
        this.userManager = userManager;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewPublicData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("VIEW PUBLIC DATA");

        btnViewPublicData.setText("View");
        btnViewPublicData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPublicDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnViewPublicData)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPublicData)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPublicDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPublicDataActionPerformed
        // TODO add your handling code here:
        List<User> publicUsers = userManager.getPublicUsers();
        StringBuilder publicData = new StringBuilder("Name\tGoal Type\tCurrent\tTarget\n");
        for (User user : publicUsers) {
            for (HealthGoal goal : user.getHealthGoals()) {
                publicData.append(user.getUsername()).append("\t")
                          .append(goal.getGoalType()).append("\t")
                          .append(goal.getCurrent()).append("\t")
                          .append(goal.getTarget()).append("\n");
            }
        }
        JOptionPane.showMessageDialog(null, publicData.toString(), "Public User Data", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewPublicDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        UserManager userManager = new UserManager(); // Initialize this appropriately
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardForm(userManager).setVisible(true); // Pass userManager to the constructor
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPublicData;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
