import java.util.List;
import javax.swing.JOptionPane;

public class HealthUpdateForm extends javax.swing.JFrame {

    private User user;
    /**
     * Creates new form HealthUpdateForm
     */
    
    public HealthUpdateForm(User user, UserManager userManager) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbGoalType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCurrent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTarget = new javax.swing.JTextField();
        btnSaveGoal = new javax.swing.JButton();
        btnTrackProgress = new javax.swing.JButton();
        btnGetBMI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Goal Type");

        cmbGoalType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weight Loss", "Muscle Strength" }));

        jLabel2.setText("Current");

        jLabel3.setText("Target");

        btnSaveGoal.setText("Save");
        btnSaveGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveGoalActionPerformed(evt);
            }
        });

        btnTrackProgress.setText("Track Progress");
        btnTrackProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackProgressActionPerformed(evt);
            }
        });

        btnGetBMI.setText("Get BMI");
        btnGetBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetBMIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveGoal)
                        .addGap(16, 16, 16)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGoalType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrackProgress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnGetBMI)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbGoalType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveGoal)
                    .addComponent(btnTrackProgress)
                    .addComponent(btnGetBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveGoalActionPerformed
        // TODO add your handling code here:
        String goalType = cmbGoalType.getSelectedItem().toString();
        try {
            double current = Double.parseDouble(txtCurrent.getText());
            double target = Double.parseDouble(txtTarget.getText());

            HealthGoal goal = new HealthGoal(goalType, current, target);
            user.addHealthGoal(goal);
            JOptionPane.showMessageDialog(null, "Health goal saved successfully.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter valid data.");
        }
    }//GEN-LAST:event_btnSaveGoalActionPerformed

    private void btnTrackProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackProgressActionPerformed
        // TODO add your handling code here:
        List<HealthGoal> goals = user.getHealthGoals();
        StringBuilder progress = new StringBuilder("Goal Type\tCurrent\tTarget\n");
        for (HealthGoal goal : goals) {
            progress.append(goal.getGoalType()).append("\t")
                    .append(goal.getCurrent()).append("\t")
                    .append(goal.getTarget()).append("\n");
        }
        JOptionPane.showMessageDialog(null, progress.toString(), "Progress", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTrackProgressActionPerformed

    private void btnGetBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetBMIActionPerformed
        // TODO add your handling code here:
        try {
            // Ensure user's profile data (height and weight) is set
            if (user.getHeight() > 0 && user.getWeight() > 0) {
                double bmi = user.calculateBMI(); // Calculate BMI using the User class method
                JOptionPane.showMessageDialog(null, "Your BMI is: " + String.format("%.2f", bmi), "BMI Result", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Please complete your profile with valid height and weight.", "Incomplete Data", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred while calculating BMI. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGetBMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         User user = new User(); // Initialize this appropriately
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(HealthUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserManager userManager = null;
                new HealthUpdateForm(user, userManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetBMI;
    private javax.swing.JButton btnSaveGoal;
    private javax.swing.JButton btnTrackProgress;
    private javax.swing.JComboBox<String> cmbGoalType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCurrent;
    private javax.swing.JTextField txtTarget;
    // End of variables declaration//GEN-END:variables
}
